version: 2
jobs:
  build:
    working_directory: ~/guacml
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          name: Setup
          command: scripts/setup
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - venv
            - lib
      - run:
          name: Linters
          command: scripts/lint
      - run:
          shell: /bin/bash
          name: test
          command: |
            [ -e venv ] && source venv/bin/activate
            export PYTHONPATH=.
            mkdir -p /tmp/test-results
            nosetests -v --with-xunit --xunit-file=/tmp/test-results/nosetests.xml
      - store_test_results:
          path: /tmp/test-results
