#!/bin/bash

function install_python_deps() {
  echo
  echo --- Install Python Dependencies

  if command -v conda >/dev/null 2>&1; then
    echo ----- using conda found in path
    echo
    while read requirement; do conda install --yes $requirement; done < requirements.txt
  else
    echo ----- no conda in path using pip
    echo
    [ ! -e venv ] && python3 -m venv venv
    source venv/bin/activate
    pip3 install -q --upgrade pip setuptools
    pip3 install -q -r requirements.txt
  fi
}

function build_xgboost() {
  echo ----- Building binary

  cd vendor/xgboost
  ./build.sh
  cd -

  echo ----- Install XGBoost Python Package

  cd vendor/xgboost/python-package
  python3 setup.py -q install
  cd -
}

function install_xgboost() {
  echo
  echo --- Make XGBoost

  if [ -d lib -a ! -d vendor ]; then
    echo --- Moving lib/ to vendor/
    mv lib vendor
  fi

  if [ ! -e vendor/xgboost ]; then
    echo --- Cloning repo into vendor/xgboost
    git clone --recursive https://github.com/dmlc/xgboost vendor/xgboost
    build_xgboost
  else
    cd vendor/xgboost
    if git checkout master &&
      git fetch origin master &&
      [ `git rev-list HEAD...origin/master --count` != 0 ] &&
      git merge origin/master
    then
      echo
      echo ----- Fetched new XGBoost source
      echo
      cd -
      build_xgboost
    else
      echo
      echo ----- XGBoost source is already up to date
      cd -
    fi
  fi
}

function install_nbstripout() {
  if ! nbstripout --is-installed ; then
    echo --- Installing nbstripout
    nbstripout --install
  fi
}

install_python_deps
install_xgboost
install_nbstripout
