run_time:
    problem_type: null
    exclude_cols: null
    eval_metric: null
    target: null
    is_time_series: False
    prediction_range: null
    time_series:
        date_split_col: null
        series_key_cols: null
        prediction_length: null

model_manager:
    reduce_features: True

models:
    xgboost: {}

cross_validation:
    date_split_col: null
    holdout_size: 0.2
    n_folds: 3

pre_processing:
    max_uniques_for_one_hot: 100
