run_time:
    problem_type: null
    exclude_cols: null
    eval_metic: null
    target: null

cross_validation:
    date_split_col: null
    holdout_size: 0.2
    n_folds: 3

pre_processing:
    max_uniques_for_one_hot: 100
